Coding-School/nittutorial/urls.py
from django.conf.urls import url
from . import views
from .views import ProductIndex, TagIndexView

urlpatterns = [
    url(r'^$',views.home, name='tut1'),
    url(r'^nittutorial/$',views.tut1, name='nittutorial'),
    url(r'^forums/',views.forums, name='tut1'),
    url(r'^blogs/',views.blogs, name='tut1'),
    url(r'^contributors/',views.contributors, name='tut1'),
    url(r'^about/',views.about, name='tut1'),
    url(r'^contact/',views.contact, name='tut1'),
    url(r'^reg/',views.manage_authors, name='manage_authors'),
    url(r'^nittutorial/(?P<title>.+)/(?P<id>\d+)/$',views.post_content, name='post_content'),
    url(r'^nittutorial/(?P<title>.+)/(?P<id>\d+)/edit/$',views.post_edit, name='post_edit'),
    url(r'^nittutorial/(?P<title>.+)/(?P<id>\d+)/delete/$',views.post_delete, name='post_delete'),
    url(r'^new/', views.tutorial_new, name='tutorial_new'),  
    url(r'^cf_profile/',views.cf_profile, name='tut1'),
    url(r'^cf_form/',views.cf_form, name='tut1'),
    url(r'^problems_find/',views.problems_find, name='tut1'),
    url(r'^problems_display/',views.problems_display, name='tut1'),
    url(r'^compile/',views.compile, name='compile'),
    url(r'^run/',views.run, name='run'),
    url(r'^editor/',views.editor, name='editor'),
    url(r'^search/$', views.search_titles,name='tagged'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.TagIndexView.as_view(),name="tagged1"),
    url(r'^accounts/login/$', views.login_view),
    url(r'^accounts/auth/$', views.login_user),
    url(r'^sign/', views.signup, name='signup'),
    url(r'^accounts/invalid/$', views.invalid_view),
    url(r'^accounts/loggedin/$', views.loggedin_view),
    url(r'^accounts/logout/$',views.logout_view),
    url(r"^accounts/register/$", views.register_user_account_view),
    url(r"^accounts/register_success/$", views.register_user_account_success_view),
    # ex: /ajSkHb
    url(r'^(?P<code_id>[-\w]+)$', views.savedCodeView, name='saved-code'),
]

Coding-School/nittutorial/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager
# Create your models here.

class Topic(models.Model):
	topicId = models.AutoField(primary_key=True)
	topicName = models.CharField(max_length=200)
	def __str__(self):
		return self.topicName

class Tutorial(models.Model):
	topicId = models.ForeignKey('Topic',db_column='topicId')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=255, blank=True)
	complexity = models.CharField(max_length = 50)
	authorId = models.IntegerField(default=123)
	rating = models.IntegerField( null = True )
	content = models.TextField(blank=True)
	createdDate = models.DateTimeField(default=timezone.now)
	publishedDate = models.DateTimeField(blank=True, null=True)
	tags = TaggableManager()
	def __str__(self):
		return self.tags.all()

	def save(self, **kwargs):
		if self.title and not self.slug:
			self.slug = slugify(self.title)
		super(Tutorial, self).save(**kwargs)

TITLE_CHOICES = (
    ('MR', 'Mr.'),
    ('MRS', 'Mrs.'),
    ('MS', 'Ms.'),
)
	
class Author(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=3, choices=TITLE_CHOICES)
    birth_date = models.DateField(blank=True, null=True)


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'title', 'birth_date']

Coding-School/nittutorial/templates/nittutorial/blogs.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
{% for tut in tutorials %}
<style>
.title{
	border-radius: 20px;
  border-color: #AFD880;
  border-width: 2px;
  border-style: solid;
  width: 300px;
  height: 40px;
  background:#AFD880;
  margin-left: 35%;
	font-family: 'Montserrat', sans-serif;
	font-size: 30px;
	text-align: center;
}
#complexity{
	font: 15px/15px 'Bree Serif', Georgia, serif;
	text-align: center;
	color:#FF6800;
}
#complexity{
	font: 15px/15px 'Bree Serif', Georgia, serif;
	text-align: center;
}
#bottom{
	display:flex;
	justify-content:space-between;
}
.content{
	font: 20px/20px 'Bree Serif', Georgia, serif;
	text-align: center;
}
#tags{
	display:flex;
	justify-content:space-between;
}
#individual{
	border-radius: 20px;
  border-color: #AFD880;
  border-width: 2px;
  border-style: solid;
  width: 80px;
  height: 40px;
  background:#AFD880;

}
#rating{
	border-radius: 20px;
  border-color: #D4AA6E;
  border-width: 2px;
  border-style: solid;
  width: 100px;
  height: 40px;
  background:#D4AA6E;
	font-family: 'Montserrat', sans-serif;
	font-size: 15px;
	text-align: center;
}
#publish{
	border-radius: 20px;
  border-color: #D4AA6E;
  border-width: 2px;
  border-style: solid;
  width: 300px;
  height: 40px;
  background:#D4AA6E;
	font-family: 'Montserrat', sans-serif;
	font-size: 15px;
	text-align: center;
}
#display{
border-radius: 20px;
  border-color: #E6D975;
  border-width: 2px;
  border-style: solid;
  width: 100%;
  height: 300px;
  background:#E6D975;
	font-family: 'Montserrat', sans-serif;
	font-size: 15px;
}
</style>
<div>
<div class="title">{{ tutorial.title }}<br></div>
<div id="complexity">Complexity is : {{ tutorial.complexity }}</div><br>
<div id="display">{{ tutorial.content }}</div><br>
<div id="bottom">
<div id="rating">Rating is : {{ tutorial.rating }}</div>
<div id="publish">Publish Date : {{ tutorial.publishedDate }}</div>
</div>
</div>
{% endfor %}
{% endblock %}

Coding-School/nittutorial/templates/nittutorial/cf_form.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
<style>
@import url(http://fonts.googleapis.com/css?family=Cabin:400);

.webdesigntuts-workshop {
	background: #151515;
	height: 100%;
	position: absolute;
	text-align: center;
	width: 100%;
}

.webdesigntuts-workshop:before,
.webdesigntuts-workshop:after {
	content: '';
	display: block;	
	height: 1px;
	left: 50%;
	margin: 0 0 0 -400px;
	position: absolute;
	width: 800px;
}

.webdesigntuts-workshop:before {
	background: #444;
	background: linear-gradient(left, #151515, #444, #151515);
	top: 192px;
}

.webdesigntuts-workshop:after {
	background: #000;
	background: linear-gradient(left, #151515, #000, #151515);	
	top: 191px;
}

.webdesigntuts-workshop form {
	background: #111;
	background: linear-gradient(#1b1b1b, #111);
	border: 1px solid #000;
	border-radius: 5px;
	box-shadow: inset 0 0 0 1px #272727;
	display: inline-block;
	font-size: 0px;
	margin: 150px auto 0;
	padding: 20px;
	position: relative;
	z-index: 1;
}

.webdesigntuts-workshop input {
	background: #222;	
	background: linear-gradient(#333, #222);	
	border: 1px solid #444;
	border-radius: 5px 0 0 5px;
	box-shadow: 0 2px 0 #000;
	color: #888;
	display: block;
	float: left;
	font-family: 'Cabin', helvetica, arial, sans-serif;
	font-size: 13px;
	font-weight: 400;
	height: 40px;
	margin: 0;
	padding: 0 10px;
	text-shadow: 0 -1px 0 #000;
	width: 200px;
}

.ie .webdesigntuts-workshop input {
	line-height: 40px;
}

.webdesigntuts-workshop input::-webkit-input-placeholder {
   color: #888;
}

.webdesigntuts-workshop input:-moz-placeholder {
   color: #888;
}

.webdesigntuts-workshop input:focus {
	animation: glow 800ms ease-out infinite alternate;
	background: #222922;
	background: linear-gradient(#333933, #222922);
	border-color: #393;
	box-shadow: 0 0 5px rgba(0,255,0,.2), inset 0 0 5px rgba(0,255,0,.1), 0 2px 0 #000;
	color: #efe;
	outline: none;
}

.webdesigntuts-workshop input:focus::-webkit-input-placeholder { 
	color: #efe;
}

.webdesigntuts-workshop input:focus:-moz-placeholder {
	color: #efe;
}

.webdesigntuts-workshop button {
	background: #222;
	background: linear-gradient(#333, #222);
	box-sizing: content-box;
	border: 1px solid #444;
	border-left-color: #000;
	border-radius: 0 5px 5px 0;
	box-shadow: 0 2px 0 #000;
	color: #fff;
	display: block;
	float: left;
	font-family: 'Cabin', helvetica, arial, sans-serif;
	font-size: 13px;
	font-weight: 400;
	height: 40px;
	line-height: 40px;
	margin: 0;
	padding: 0;
	position: relative;
	text-shadow: 0 -1px 0 #000;
	width: 80px;
}	

.webdesigntuts-workshop button:hover,
.webdesigntuts-workshop button:focus {
	background: #292929;
	background: linear-gradient(#393939, #292929);
	color: #5f5;
	outline: none;
}

.webdesigntuts-workshop button:active {
	background: #292929;
	background: linear-gradient(#393939, #292929);
	box-shadow: 0 1px 0 #000, inset 1px 0 1px #222;
	top: 1px;
}

@keyframes glow {
    0% {
		border-color: #393;
		box-shadow: 0 0 5px rgba(0,255,0,.2), inset 0 0 5px rgba(0,255,0,.1), 0 2px 0 #000;
    }	
    100% {
		border-color: #6f6;
		box-shadow: 0 0 20px rgba(0,255,0,.6), inset 0 0 10px rgba(0,255,0,.4), 0 2px 0 #000;
    }
}
</style>
<section class="webdesigntuts-workshop">
	<form method="post" action="/cf_profile/">	
	{% csrf_token %}	    
		<input type="text" name="user" placeholder="Enter username" value="" required autofocus>	    	
		<button>Search</button>
	</form>
</section>
{% endblock %}

Coding-School/nittutorial/templates/nittutorial/cf_profile.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
{% for key in data %}
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
       <br>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ key.handle }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Handle:</td>
                        <td>{{ key.handle }}</td>
                      </tr>
                      <tr>
                        <td>Rating:</td>
                        <td>{{ key.rating }}</td>
                      </tr>
                      <tr>
                        <td>Contribution</td>
                        <td>{{ key.contribution }}</td>
                      </tr>
                   
                         <tr>
                             <tr>
                        <td>MaxRating</td>
                        <td>{{ key.maxRating }}</td>
                      </tr>
                        <tr>
                        <td>Rank</td>
                        <td>{{ key.rank }}</td>
                      </tr>
                      <tr>
                        <td>Profile Link</td>
                        <td><a href="http://codeforces.com/profile/{{ key.handle }}">Click Here</a></td>
                      </tr>                 
                      </tr>
                     
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
{% endblock %}

Coding-School/nittutorial/templates/nittutorial/contributors.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
<h1>Sunny Aggarwal</h1>
<div class="image_size">
<img src="{% static 'nittutorial/images/sunny.jpg ' %}"/>
</div>
<h1>Alok Tomar</h1>
<div class="image_size">
<img src="{% static 'nittutorial/images/alok.jpg ' %}"/>
</div>
{% endblock %}

Coding-School/nittutorial/templates/nittutorial/custom_editor.html
{% load staticfiles %}
{% load mkrange %}
<!DOCTYPE HTML>

<html>
	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<script src="{% static 'nittutorial/js/editor.js' %}"></script>
		<script>
			$(document).ready(function() {
				$("#id_content").Editor();
			});
		</script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link href="{% static 'nittutorial/css/editor.css' %}" type="text/css" rel="stylesheet"/>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<h2 class="demo-text">LineControl Demo</h2>
				<div class="container">
					<div class="row">
						<div class="col-lg-12 nopadding">
							<textarea id="id_content"></textarea> 
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid footer">
			<p class="pull-right">&copy; Suyati Technologies <script>document.write(new Date().getFullYear())</script>. All rights reserved.</p>
		</div>
	</body>
</html>

Coding-School/nittutorial/templates/nittutorial/forums.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}

{% block content %}
    {% for tut in tutorials %}
    <style>
    #author{
        margin-left: -80%;
    }
    </style>    
        <div class="col-md-6 col-sm-6">
            
             <div class="card-container">
           
                <div class="card">
                    <div class="front">
                        < <div class="user"> 
                            <img class="img-circle" src="{% static 'nittutorial/images/rotating_card_profile3.png ' %}"/> 
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name"><a href="{% url 'post_content' title=tut.title id=tut.pk %}" class="side_color">{{ tut.title }}</a></h3>

                               <h4> <p class="text-center" id="author"><span class="label label-success">
                                    Authored By: &nbsp; {{tut.authorId}}
                                    </span></p></h4>
                                <br>
                                <h5><i class="fa fa-map-marker fa-fw text-muted"></i> <strong>Difficulty</strong> : {{tut.complexity}}</h5>
                                <h5><i class="fa fa-building-o fa-fw text-muted"></i> <strong>Published Date </strong>: {{ tut.publishedDate|date:"M d, Y"  }}</h5>
                                <p><span class="label label-danger">
                                    segment tree
                                    </span>&nbsp;&nbsp;<span class="label label-danger">
                                    dp
                                    </span></p>

                            </div>
                            <div class="footer">
                            </div>
                        </div>
                    </div> <!-- end front panel -->
                    <div class="back">
                        <div class="footer">
                            <div class="social-links text-center" id="author">
                                <a href="http://cretive-tim.com" class="facebook"><i class="fa fa-facebook fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="google"><i class="fa fa-google-plus fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="twitter"><i class="fa fa-twitter fa-fw"></i></a>
                            </div>
                        </div>
                    </div> <!-- end back panel -->
                </div> <!-- end card -->
            </div> <!-- end card-container -->
        </div> <!-- end col sm 3 -->
    {% endfor %}
{% endblock %}

Coding-School/nittutorial/templates/nittutorial/loggedin.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}

{% block content %}

	<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
        <A href="/accounts/logout" id="logout">Logout</A>
       <br>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{full_name }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Department:</td>
                        <td>Computer Engineering</td>
                      </tr>
                      <tr>
                        <td>Hire date:</td>
                        <td>03/05/2016</td>
                      </tr>
                      <tr>
                        <td>Date of Birth</td>
                        <td>28/01/1995</td>
                      </tr>
                   
                         <tr>
                             <tr>
                        <td>Gender</td>
                        <td>Male</td>
                      </tr>
                        <tr>
                        <td>Home Address</td>
                        <td>Nit Kurukshetra</td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><a href="mailto:{{ email }} ">{{ email }}</a></td>
                      </tr>
                        <td>Phone Number</td>
                        <td>9466904200<br><br>
                        </td>
                           
                      </tr>
                     
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>

{% endblock %}

Coding-School/nittutorial/templates/nittutorial/logout.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}

{% block content %}

	<H2>Goodbye. I miss you so bad, it makes my belly hurt.</H2>

	<a href="/accounts/login"><h2>Login</h2></a>

{% endblock %}

Coding-School/nittutorial/templates/nittutorial/post_edit.html
{% extends 'nittutorial/homepage.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
	<script src="{% static 'nittutorial/js/editor.js' %}"></script>
		<script>
			$(document).ready(function() {
				var con = $("#id_content").text();
				$("#id_content").Editor();
				$("#id_content").Editor("setText",con);
			$("#s2").click(function () {
                    $('#id_content').text($('#id_content').Editor("getText", ["<button>"]));
                    //alert($('#id_content').text());
                });
			});
		</script>
		<link href="{% static 'nittutorial/css/editor.css' %}" type="text/css" rel="stylesheet"/>
	<div class="container">
    <h1>Tutorial Edit</h1>
   
    <form method="post">{% csrf_token %}
    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.topicId.errors %}
    		
    		{% for error in form.topicId.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    	{% endfor %}
    		
		{% endif %}
                <label for="{{ form.topicId.id_for_label }}">Select Topic: </label>
                
                                <span class="form-control">
                                {{form.topicId}}</span>
                              <!--   <select class="form-control" id="id_topicId">
                                 
                                </select> -->
                <p class="help-block">Select Topic of Tutorial</p>
    </div></div>
    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.title.errors %}
    		
    		{% for error in form.title.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    	
    		{% endfor %}
		{% endif %}
                <label for="{{ form.title.id_for_label }}">Title</label>
                <input class="form-control" id="id_title" name="title" value="{{form.title.value}}"> 
                <p class="help-block">Enter Title of Tutorial</p>
    </div></div>
   			
     <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.subject.errors %}
    		
    		{% for error in form.complexity.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    		{% endfor %}
		{% endif %}
                <label for="{{ form.complexity.id_for_label }}">Complexity</label>
                 <select class="form-control" id="id_complexity1" name="complexity" value="{{form.complexity.value}}">
                                  <option>Easy</option>
                                  <option>Medium</option>
                                  <option>Hard</option>
                                  <option>Expert</option>
                 </select>
                <p class="help-block">Enter Complexity of Tutorial</p>
    </div></div>
    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.rating.errors %}		
    		{% for error in form.rating.errors %}
    		 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    	{% endfor %}
    		
		{% endif %}
                <label for="{{ form.rating.id_for_label }}">Rating</label>
                <input class="form-control" id="id_rating" name="rating" value='{{form.rating.value}}'> 
                <p class="help-block">Expected Rating </p>
    </div></div>
    
    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.slug.errors %}
    		
    		{% for error in form.slug.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    	{% endfor %}
    		
		{% endif %}
                <label for="{{ form.slug.id_for_label }}">Slug (Optional)</label>
                <input class="form-control" id="id_slug" name="slug" value="{{form.slug.value}}"> 
                <p class="help-block"> Tutorial Link</p>
    </div></div>

    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.tags.errors %}
    		
    		{% for error in form.tags.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
    	{% endfor %}
    		
		{% endif %}
                <label for="{{ form.tags.id_for_label }}">Tags</label>
                <input class="form-control" id="id_tags" name="tags" value="{% for e in form.tags %} 
                													{{ e.slug}}
                												{% endfor %}"> 
                <p class="help-block">Tags(Comma seperated) </p>
    </div></div>
    
    <div class="row">
    <div class="col-lg-8 form-group">
   		{% if form.content.errors %}
    		
    		{% for error in form.content.errors %}
        	 <div class="alert alert-danger">
                         <strong>Oh snap!</strong> {{ error|escape }} 
        	</div>
        	    	{% endfor %}
    		
		{% endif %}
                <label for="{{ form.content.id_for_label }}">Tutorial Content</label>
                <input class="form-control" id="id_content" name="content" value="{{form.content.value}}"> 
                <p class="help-block">Add content of Tutorial</p>
    </div></div>

    <button type="submit" id="s2" class="btn  btn-primary">SUBMIT</button>
</form></div>

{%endblock%}

Coding-School/nittutorial/templates/nittutorial/registration1.html
{% extends 'nittutorial/index.html' %}
{% load staticfiles %}
{% load mkrange %}
{% block content %}
 <form action="/accounts/register/" method="post">{% csrf_token %} 
 <div class="field-wrap">

            
              <label>
                UserName<span class="req">*</span>
              </label>
              {{form.email}}
              <!-- <input type="text" required autocomplete="off" /> -->
            </div>
        
            <div class="field-wrap">
              <label>
                FullName<span class="req">*</span>
              </label>
              {{form.password1}}
              <!-- <input type="text"required autocomplete="off"/> -->
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
           {{form.email}}
          </div>
          
          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            {{form.password2}}
            <!-- <input type="password"required autocomplete="off"/> -->
          </div>
          
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>
{% endblock %}